# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Birdhome
author:
  email: ppu7haxj@duck.com 
  matrix: "@alnvyuitw34:matrix.org"
  name:  nieve
description: >- # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://birdhome.stellar.agew.tech" # the base hostname & protocol for your site, e.g. http://example.com

collections_dir: collections

# Build settings
#remote_theme: jekyll/minima
#theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-postcss-v2
  
postcss:
  script: node_modules/.bin/postcss
  config: postcss.config.js

postcss:
  cache: false

minima:
  skin: auto
  date_format: "%-d %b, %Y"
  social_links:
    - platform: simplex
      user_url: "https://simplex.chat/contact#/?v=2-5&smp=smp%3A%2F%2FUkMFNAXLXeAAe0beCa4w6X_zp18PwxSaSjY17BKUGXQ%3D%40smp12.simplex.im%2FlMAI_ct62DZ8LSS5w-TtWG4G8pT1kVr_%23%2F%3Fv%3D1-2%26dh%3DMCowBQYDK2VuAyEAbhB6mjf8jT0GO3m5eqLEgRLZ7THEJRcnmXiKn-7aDHc%253D%26srv%3Die42b5weq7zdkghocs3mgxdjeuycheeqqmksntj57rmejagmg4eor5yd.onion"
    - { platform: codeberg, user_url: "https://codeberg.org/nieve" }
    - { platform: github, user_url: "https://github.com/ac615223s5" }
    - { platform: youtube, user_url: "https://www.youtube.com/channel/UCm8GhQcqqMeWz67SiMgCwTQ" }
    

header_pages:
  - pages/blog.markdown
  - pages/algorithm.md
  - pages/coding.md
  - games/index.md
  - pages/art.md
  - pages/music.md
  - pages/wormhole.md
  - pages/credits.md  
  - pages/images.md

#show_excerpts: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
